# Generated by Django 6.0.1 on 2026-03-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_delete_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ktp_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_photos/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='national_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
