# Generated by Django 5.2.4 on 2026-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_contactmessage_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(db_index=True, max_length=180),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at', 'is_resolved'], name='hospital_co_created_671058_idx'),
        ),
    ]
