# Generated by Django 5.2.4 on 2026-03-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='hospital_ap_status_abfe3d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['-booked_at'], name='hospital_ap_booked__d2c6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='hospital_ap_doctor__8632ec_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient'], name='hospital_ap_patient_08e863_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', '-booked_at'], name='hospital_ap_status_8f2a79_idx'),
        ),
    ]
