# Generated by Django 5.2.4 on 2026-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_add_appointment_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_new_patient',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
