# Generated by Django 4.2 on 2026-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
