# Generated by Django 4.2 on 2026-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Menunggu'), ('called', 'Dipanggil'), ('serving', 'Dilayani'), ('done', 'Selesai'), ('absent', 'Tidak Hadir')], db_index=True, default='waiting', max_length=20),
        ),
    ]
