# Generated by Django 5.2.12 on 2026-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, default='bi-hospital', max_length=60),
        ),
    ]
