# Generated by Django 5.2.12 on 2026-05-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='McuPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=320)),
                ('content', models.TextField()),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('checklist', models.TextField(blank=True)),
                ('preparation', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='mcu/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='mcu/content/')),
                ('content_image_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCU Package',
                'verbose_name_plural': 'MCU Packages',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
