# Generated by Django 5.2.12 on 2026-05-24 11:48

import django.db.models.deletion
from django.db import migrations, models


def seed_default_footer(apps, schema_editor):
    FooterSetting = apps.get_model('hospital', 'FooterSetting')
    FooterSection = apps.get_model('hospital', 'FooterSection')
    FooterLink = apps.get_model('hospital', 'FooterLink')

    FooterSetting.objects.get_or_create(
        pk=1,
        defaults={
            'site_name': 'RS Gunung Maria Tomohon',
            'hospital_code': '7173051',
            'tagline': 'Melayani dengan kasih,\ndemi kesehatan Anda.',
            'dashboard_label': 'Dashboard',
            'dashboard_url': '/dashboard/',
            'show_dashboard_link': True,
        },
    )

    sections = [
        ('about', 'Tentang Kami', 'links', 1, [
            ('Profil Rumah Sakit', '/about/', '', 1, False),
            ('Visi & Misi', '/about/', '', 2, False),
            ('Mitra & Kerjasama', '/mitra/', '', 3, False),
            ('Akreditasi', '/about/', '', 4, False),
        ]),
        ('services', 'Layanan', 'links', 2, [
            ('Jadwal Dokter', '/doctors/', '', 1, False),
            ('Buat Janji Temu', '/appointments/', '', 2, False),
            ('Cek Antrian', '/cek-antrian/', '', 3, False),
            ('Paket MCU', '/paket-mcu/', '', 4, False),
            ('Fasilitas & Layanan', '/services/', '', 5, False),
        ]),
        ('info', 'Informasi', 'links', 3, [
            ('Artikel Kesehatan', '/artikel/', '', 1, False),
            ('Berita Terbaru', '/berita/', '', 2, False),
            ('Pencarian', '/search/', '', 3, False),
        ]),
        ('contact', 'Kontak', 'contact', 4, [
            ('Jl. Sejahtera No. 282, Kel. Kolongan, Tomohon', '', 'bi-geo-alt', 1, False),
            ('(0431) 351008', 'tel:0431351008', 'bi-telephone', 2, False),
            ('rsgunungmaria@yahoo.co.id', 'mailto:rsgunungmaria@yahoo.co.id', 'bi-envelope', 3, False),
            ('Senin - Sabtu, 08.00 - 16.00', '', 'bi-clock', 4, False),
        ]),
        ('social', 'Terhubung dengan Kami', 'social', 5, [
            ('WhatsApp', 'https://wa.me/62811351008', 'bi-whatsapp', 1, True),
            ('Instagram', '#', 'bi-instagram', 2, False),
            ('Facebook', '#', 'bi-facebook', 3, False),
            ('YouTube', '#', 'bi-youtube', 4, False),
        ]),
    ]

    for key, title, section_type, order, links in sections:
        section, _ = FooterSection.objects.get_or_create(
            title=title,
            defaults={'section_type': section_type, 'order': order, 'is_active': True},
        )
        for label, url, icon, link_order, open_new_tab in links:
            FooterLink.objects.get_or_create(
                section=section,
                label=label,
                defaults={
                    'url': url,
                    'icon': icon,
                    'order': link_order,
                    'is_active': True,
                    'open_new_tab': open_new_tab,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('section_type', models.CharField(choices=[('links', 'Menu Link'), ('contact', 'Kontak'), ('social', 'Sosial Media')], default='links', max_length=20)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='RS Gunung Maria Tomohon', max_length=160)),
                ('hospital_code', models.CharField(blank=True, default='7173051', max_length=80)),
                ('tagline', models.TextField(blank=True, default='Melayani dengan kasih,\ndemi kesehatan Anda.')),
                ('dashboard_label', models.CharField(blank=True, default='Dashboard', max_length=80)),
                ('dashboard_url', models.CharField(blank=True, default='/dashboard/', max_length=500)),
                ('show_dashboard_link', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Contoh: bi-whatsapp, bi-geo-alt', max_length=60)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='hospital.footersection')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_default_footer, migrations.RunPython.noop),
    ]
