# Generated by Django 5.2.12 on 2026-05-24 11:57

import django.db.models.deletion
from django.db import migrations, models


def seed_home_article_feature(apps, schema_editor):
    Article = apps.get_model('hospital', 'Article')
    HomeArticleFeature = apps.get_model('hospital', 'HomeArticleFeature')
    article = Article.objects.filter(is_published=True).order_by('-created_at').first()
    HomeArticleFeature.objects.get_or_create(
        pk=1,
        defaults={
            'article': article,
            'kicker': 'Artikel Pilihan',
            'primary_label': 'Baca Selengkapnya',
            'secondary_label': 'Lihat Semua Artikel',
            'secondary_url': '/artikel/',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_footersection_footersetting_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeArticleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Artikel Pilihan', max_length=120)),
                ('title_override', models.CharField(blank=True, max_length=220)),
                ('excerpt_override', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/article_feature/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('primary_label', models.CharField(default='Baca Selengkapnya', max_length=80)),
                ('primary_url', models.CharField(blank=True, max_length=500)),
                ('secondary_label', models.CharField(default='Lihat Semua Artikel', max_length=80)),
                ('secondary_url', models.CharField(blank=True, default='/artikel/', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_features', to='hospital.article')),
            ],
            options={
                'verbose_name': 'Home Article Feature',
                'verbose_name_plural': 'Home Article Feature',
            },
        ),
        migrations.RunPython(seed_home_article_feature, migrations.RunPython.noop),
    ]
